### Importing necessary libraries

In [1]:
import pandas as pd

### Data Collection

In [2]:
env_data=pd.read_csv("environmental_data.csv")
env_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

### Data Understanding

In [3]:
env_data.shape

(158, 10)

In [4]:
env_data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
153    False
154    False
155    False
156    False
157    False
Length: 158, dtype: bool

In [5]:
env_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [6]:
env_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

#### Data Cleaning

In [7]:
env_data=env_data.drop(columns=["Unnamed: 0","Temp C"],axis=1)
env_data

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [8]:
del env_data["Ozone"]

In [9]:
env_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4        NaN  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [10]:
env_data[env_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [11]:
env_data.groupby("Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [12]:
env_data["Solar.R"]=env_data.groupby("Weather")["Solar.R"].transform(lambda x:x.fillna(x.mean().round()))
env_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [13]:
env_data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [14]:
env_data[env_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [15]:
env_data.dropna(inplace=True)

In [16]:
env_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [17]:
env_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [18]:
env_data["Month"].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [19]:
env_data["Month"].replace(to_replace='May',value=5,inplace=True)
env_data

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_10448\3714026048.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  env_data["Month"].replace(to_replace='May',value=5,inplace=True)

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[155 rows x 7 columns]

In [20]:
env_data.head(30)

    Solar.R  Wind Month  Day  Year  Temp Weather
0     190.0   7.4     5    1  2010    67       S
1     118.0   8.0     5    2  2010    72       C
2     149.0  12.6     5    3  2010    74      PS
3     313.0  11.5     5    4  2010    62       S
4     193.0  14.3     5    5  2010    56       S
5     192.0  14.9     5    6  2010    66       C
6     299.0   8.6     5    7  2010    65      PS
7      99.0  13.8     5    8  2010    59       C
8      19.0  20.1     5    9  2010    61      PS
9     194.0   8.6     5   10  2010    69       S
10    192.0   6.9     5   11  2010    74       C
11    256.0   9.7     5   12  2010    69      PS
12    290.0   9.2     5   13  2010    66       S
13    274.0  10.9     5   14  2010    68       S
14     65.0  13.2     5   15  2010    58       C
15    334.0  11.5     5   16  2010    64       S
16    307.0  12.0     5   17  2010    66       S
17     78.0  18.4     5   18  2010    57       C
18    322.0  11.5     5   19  2010    68      PS
19     44.0   9.7     5   20  2010    62       S
20      8.0   9.7     5   21  2010    59       S
21    320.0  16.6     5   22  2010    73       C
22     25.0   9.7     5   23  2010    61      PS
23     92.0  12.0     5   24  2010    61       C
24     66.0  16.6     5   25  2010    57      PS
25    266.0  14.9     5   26  2010    58       C
26    174.0   8.0     5   27  2010    57      PS
27     13.0  12.0     5   28  2010    67       S
28    252.0  14.9     5   29  2010    81       S
29    223.0   5.7     5   30  2010    79       C

In [21]:
env_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [22]:
env_data["Month"]=env_data["Month"].astype("int")
env_data

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [23]:
env_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [24]:
env_data_1=env_data.copy()
env_data_1

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [25]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le_enc=LabelEncoder()
env_data_1["Weather"]=le_enc.fit_transform(env_data_1["Weather"])
env_data_1

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]